#!/usr/bin/env php
<?php
// SPDX-License-Identifier: BSD-3-Clause

use AKlump\Directio\Command\FixturesCommand;
use AKlump\Directio\Command\ImportCommand;
use AKlump\Directio\Command\InitializeCommand;
use AKlump\Directio\Command\UpdateCommand;
use Symfony\Component\Console\Application;

foreach ([
           __DIR__ . '/../../autoload.php',
           __DIR__ . '/../vendor/autoload.php',
           __DIR__ . '/vendor/autoload.php',
         ] as $file) {
  if (file_exists($file)) {
    $class_loader = require_once $file;
    break;
  }
}

$application = new Application();
$application->setName('Directio: Persistent Task Manager');
$application->add(new InitializeCommand());
$application->add(new UpdateCommand());
$application->add(new ImportCommand());
$application->add(new FixturesCommand());
$application->run();
